import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>{/* Add your custom <head> content here */}</Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

/*
This file is used to customize the HTML document that Next.js generates. It allows you to add custom HTML elements, scripts, and modify the overall structure of the document.
You can use this file to include third-party scripts, add metadata, or change the default HTML structure for SEO purposes.
Unlike _app.js, _document.js is only executed on the server during the initial render.
generated by Chatgpt */
